INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T12:15:00', 'deluxe', 1, 'Mulan');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T14:45:00', 'deluxe', 1, 'Frozen 2');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T18:45:00', 'deluxe', 1, 'Avengers: Infinity War');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T21:45:00', 'deluxe', 1, 'Avengers: Endgame');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T12:00:00', 'deluxe', 2, 'Frozen 2');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T14:15:00', 'deluxe', 2, 'How To Train Your Dragon: Hidden World');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T17:15:00', 'deluxe', 2, 'Spiderman: Into The Spiderverse');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T20:15:00', 'deluxe', 2, 'Frozen 2');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T22:40:00', 'deluxe', 2, 'Mulan');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T12:15:00', 'standard', 3, 'How To Train Your Dragon: Hidden World');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T14:45:00', 'standard', 3, 'Avengers: Endgame');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T18:15:00', 'standard', 3, 'Mulan');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T21:15:00', 'standard', 3, 'Frozen 2');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T12:00:00', 'standard', 4, 'How To Train Your Dragon: Hidden World');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T14:55:00', 'standard', 4, 'Mulan');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T17:15:00', 'standard', 4, 'Spiderman: Into The Spiderverse');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T20:15:00', 'standard', 4, 'How To Train Your Dragon: Hidden World');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T22:35:00', 'standard', 4, 'Spiderman: Into The Spiderverse');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T12:15:00', 'standard', 5, 'Spiderman: Into The Spiderverse');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T14:35:00', 'standard', 5, 'Spiderman: Into The Spiderverse');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T16:55:00', 'standard', 5, 'Spiderman: Into The Spiderverse');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T19:15:00', 'standard', 5, 'Spiderman: Into The Spiderverse');
INSERT INTO screenings (movie_date_time, screen_type, screen_number, movie_name) VALUES ('2020-06-10T21:45:00', 'standard', 5, 'Spiderman: Into The Spiderverse');

INSERT INTO user (username, password, matching_password, roles, active, email, forename, surname) VALUES ('test', 'root', 'root', 'ROLE_USER', TRUE, 'test@aol.com', 'Jim', 'Jimmerson');